[phases.setup]
# Include any necessary system packages
apt_pkgs = ["build-essential", "libpq-dev", "libopencv-dev"]

[phases.install]
# Install Python dependencies
commands = [
  "pip install -r requirements.txt"
]

[phases.start]
# Start the Django application using Gunicorn
commands = [
  "gunicorn PNRStatusTracker.wsgi:application --bind 0.0.0.0:8000"
]

[phases.build]
# Any additional build steps can be added here
commands = []