# Generated by Django 4.2.20 on 2025-03-16 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPNRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pnr', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_pnr', message='PNR must be a 10-digit number.', regex='^\\d{10}$')])),
                ('isWL', models.BooleanField()),
                ('isChartPrepared', models.BooleanField()),
                ('currentStatusDetails1', models.CharField(max_length=20)),
                ('currentStatusDetails2', models.CharField(max_length=20)),
                ('currentStatusDetails3', models.CharField(max_length=20)),
                ('currentStatusDetails4', models.CharField(max_length=20)),
                ('currentStatusDetails5', models.CharField(max_length=20)),
                ('currentStatusDetails6', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Email PNR Status',
                'verbose_name_plural': 'Email PNR Statuses',
                'unique_together': {('email', 'pnr')},
            },
        ),
    ]
