# Generated by Django 4.2.20 on 2025-03-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_emailpnrstatus_ischartprepared_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailpnrstatus',
            old_name='isChartPrepared',
            new_name='chartstatus',
        ),
    ]
